### ISSUE TITLE
Add mailbox for inactive chat users

### ISSUE THREAD

**Issue by Snailbutt** [moneypot/shiba#28]
Message users who are not online. Use "!leave "username" "message here" 

Upon the set users chat message after the message is to be sent, Shiba pastes the message and who it is from. Example:

2:50 Ryan: !leave Ryan2 Hey Ryan, long time no see
*Ryan2 goes online 3 hours later*
5:50 Ryan2: Hi guys
5:50 Shiba: @Ryan2, Ryan says: Hey Ryan, long time no see

**Comment by kungfuant** [comment]
I don't think that should be implemented in a chat bot. Rather you should convince Ryan to implement private messages server side.
